"""SC2_FIXED_4096: import reviewed fixed-grid wave records without recomputing.

Regenerate research first with Documentation/game-code-analysis/extract_enemy_waves.py.
Run this script from any directory to update the tracked application dataset.
"""
import csv
from decimal import Decimal
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
research = ROOT / 'Documentation/game-code-analysis'
csv_path = research / 'enemy-waves.csv'
evidence = json.loads((research / 'source-evidence.json').read_text(encoding='utf-8'))
policy = evidence['numeric_policy']
if policy['model'] != 'fixed_4096' or policy['rounding'] != 'truncate-toward-zero':
    raise ValueError('Regenerate the fixed_4096 extraction with its default rounding policy first.')
for name, digest in evidence['inputs_sha256'].items():
    if hashlib.sha256((ROOT / name).read_bytes()).hexdigest() != digest:
        raise ValueError(f'Stale extracted data: source hash changed for {name}')
fields = ['wave', 'hp', 'shield', 'armor', 'shield_armor', 'spawn_batches', 'base_creeps_per_batch',
          'spawned_creeps_per_lane', 'full_clear_kills_per_lane', 'revival_multiplier',
          'base_interval_game_seconds', 'waits_per_batch', 'base_spawn_phase_game_seconds',
          'base_post_spawn_game_seconds', 'base_nominal_combat_game_seconds',
          'dt_interval_game_seconds', 'dt_spawn_phase_game_seconds', 'dt_post_spawn_game_seconds',
          'dt_nominal_combat_game_seconds', 'intrinsic_damage_taken_fraction',
          'creep_penalty_threshold_per_lane', 'creep_penalty_check_interval_game_seconds',
          'toc_torment_after_round_start_update', 'reachability', 'count_basis',
          'catalog_missing_numeric_fields_assumed_zero']
text_fields = set(fields[-3:])
tables = {mode: [] for mode in ['Classic', 'Eternal', 'Hyper', 'ToC']}
for row in csv.DictReader(csv_path.open(encoding='utf-8', newline='')):
    if row['numeric_model'] != 'fixed_4096' or row['numeric_rounding'] != 'truncate-toward-zero':
        raise ValueError('The importer accepts only fixed_4096 rows, never decimal reference rows.')
    values = []
    for field in fields:
        value = row[field]
        if field in text_fields:
            values.append(value)
        elif value == '':
            values.append(None)
        else:
            decimal = Decimal(value)
            assert decimal * 4096 == (decimal * 4096).to_integral_value(), field
            values.append(int(decimal) if decimal == decimal.to_integral_value() else float(decimal))
    tables[row['mode']].append(values)
assert sum(map(len, tables.values())) == 990
payload = {'metadata': {'sourceSha256': evidence['source_sha256'],
    'extractedCsvSha256': hashlib.sha256(csv_path.read_bytes()).hexdigest(),
    'numericPolicy': evidence['numeric_policy'], 'sourceVersion': 'attached-map-23.0',
    'hyperBasis': 'Eternal', 'hyperLastRegularTableRound': 114, 'hyperEndBoundary': 115,
    'limitations': ['Provisional rounding; nominal timers, not game-loop scheduling.',
                   'Eternal 151-250 uses literal nested-branch behavior; runtime confirmation pending.',
                   'ToC lane branch and torment update ordering require runtime confirmation.']},
    'fields': fields, 'tables': tables}
path = ROOT / 'src/data/euna/calculator/enemyWaves.js'
path.write_text('// SC2_FIXED_4096: generated by scripts/calculator/generate-enemy-waves.py; do not edit.\nexport default '
                + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'Generated {path.relative_to(ROOT)}: 990 fixed-grid records.')
